function removeminiport ($odstranitport){
$allLines = (cmd /c "devcon-x64 /findall $odstranitport") | Out-String
[string[]]$radky = $allLines.Split("`n",[System.StringSplitOptions]::RemoveEmptyEntries)
foreach ($element in $radky) {
if($element -Like "*WAN Miniport*") {
$pos = $element.IndexOf("   ")
$leftPart = $element.Substring(0, $pos)
$leftPart = $leftpart.trim()
if($leftPart.Length -gt 0 ) {
echo($leftPart)
& $global:cesta sethwid "@$leftPart" := +*msloop !$odstranitport
		& $global:cesta update "$global:ovladac" *msloop
		& $global:cesta remove *msloop
		& $global:cesta remove "@$leftPart"
}}}}
[string] $global:cesta = (Get-Location -PSProvider FileSystem).ProviderPath + "\devcon-x64.exe"
$global:ovladac = "$env:windir\inf\netloop.inf"
if(Test-Path $ovladac){
	if(Test-Path $cesta){
		removeminiport "MS_AgileVpnMiniport"
		removeminiport "MS_NdisWanIp"
		removeminiport "MS_NdisWanIpv6"
		removeminiport "MS_NdisWanBh"
		removeminiport "MS_L2tpMiniport"
		removeminiport "MS_PppoeMiniport"
		removeminiport "MS_PptpMiniport"
		removeminiport "MS_SstpMiniport"
	}}

# SIG # Begin signature block
# MIIWhgYJKoZIhvcNAQcCoIIWdzCCFnMCAQExCzAJBgUrDgMCGgUAMGkGCisGAQQB
# gjcCAQSgWzBZMDQGCisGAQQBgjcCAR4wJgIDAQAABBAfzDtgWUsITrck0sYpfvNR
# AgEAAgEAAgEAAgEAAgEAMCEwCQYFKw4DAhoFAAQUk92VT9cciUumbna3FsEFayzQ
# q3OgghFCMIIEFDCCAvygAwIBAgILBAAAAAABL07hUtcwDQYJKoZIhvcNAQEFBQAw
# VzELMAkGA1UEBhMCQkUxGTAXBgNVBAoTEEdsb2JhbFNpZ24gbnYtc2ExEDAOBgNV
# BAsTB1Jvb3QgQ0ExGzAZBgNVBAMTEkdsb2JhbFNpZ24gUm9vdCBDQTAeFw0xMTA0
# MTMxMDAwMDBaFw0yODAxMjgxMjAwMDBaMFIxCzAJBgNVBAYTAkJFMRkwFwYDVQQK
# ExBHbG9iYWxTaWduIG52LXNhMSgwJgYDVQQDEx9HbG9iYWxTaWduIFRpbWVzdGFt
# cGluZyBDQSAtIEcyMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAlO9l
# +LVXn6BTDTQG6wkft0cYasvwW+T/J6U00feJGr+esc0SQW5m1IGghYtkWkYvmaCN
# d7HivFzdItdqZ9C76Mp03otPDbBS5ZBb60cO8eefnAuQZT4XljBFcm05oRc2yrmg
# jBtPCBn2gTGtYRakYua0QJ7D/PuV9vu1LpWBmODvxevYAll4d/eq41JrUJEpxfz3
# zZNl0mBhIvIG+zLdFlH6Dv2KMPAXCae78wSuq5DnbN96qfTvxGInX2+ZbTh0qhGL
# 2t/HFEzphbLswn1KJo/nVrqm4M+SU4B09APsaLJgvIQgAIMboe60dAXBKY5i0Eex
# +vBTzBj5Ljv5cH60JQIDAQABo4HlMIHiMA4GA1UdDwEB/wQEAwIBBjASBgNVHRMB
# Af8ECDAGAQH/AgEAMB0GA1UdDgQWBBRG2D7/3OO+/4Pm9IWbsN1q1hSpwTBHBgNV
# HSAEQDA+MDwGBFUdIAAwNDAyBggrBgEFBQcCARYmaHR0cHM6Ly93d3cuZ2xvYmFs
# c2lnbi5jb20vcmVwb3NpdG9yeS8wMwYDVR0fBCwwKjAooCagJIYiaHR0cDovL2Ny
# bC5nbG9iYWxzaWduLm5ldC9yb290LmNybDAfBgNVHSMEGDAWgBRge2YaRQ2XyolQ
# L30EzTSo//z9SzANBgkqhkiG9w0BAQUFAAOCAQEATl5WkB5GtNlJMfO7FzkoG8IW
# 3f1B3AkFBJtvsqKa1pkuQJkAVbXqP6UgdtOGNNQXzFU6x4Lu76i6vNgGnxVQ380W
# e1I6AtcZGv2v8Hhc4EvFGN86JB7arLipWAQCBzDbsBJe/jG+8ARI9PBw+DpeVoPP
# PfsNvPTF7ZedudTbpSeE4zibi6c1hkQgpDttpGoLoYP9KOva7yj2zIhd+wo7AKvg
# IeviLzVsD440RZfroveZMzV+y5qKu0VN5z+fwtmK+mWybsd+Zf/okuEsMaL3sCc2
# SI8mbzvuTXYfecPlf5Y1vC0OzAGwjn//UYCAp5LUs0RGZIyHTxZjBzFLY7Df8zCC
# BCgwggMQoAMCAQICCwQAAAAAAS9O4TVcMA0GCSqGSIb3DQEBBQUAMFcxCzAJBgNV
# BAYTAkJFMRkwFwYDVQQKExBHbG9iYWxTaWduIG52LXNhMRAwDgYDVQQLEwdSb290
# IENBMRswGQYDVQQDExJHbG9iYWxTaWduIFJvb3QgQ0EwHhcNMTEwNDEzMTAwMDAw
# WhcNMTkwNDEzMTAwMDAwWjBRMQswCQYDVQQGEwJCRTEZMBcGA1UEChMQR2xvYmFs
# U2lnbiBudi1zYTEnMCUGA1UEAxMeR2xvYmFsU2lnbiBDb2RlU2lnbmluZyBDQSAt
# IEcyMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAsk8U5xC+1yZyqzaX
# 71O/QoReWNGKKPxDRm9+KERQC3VdANc8CkSeIGqk90VKN2Cjbj8S+m36tkbDaqO4
# DCcoAlco0VD3YTlVuMPhJYZSPL8FHdezmviaJDFJ1aKp4tORqz48c+/2KfHINdAw
# e39OkqUGj4fizvXBY2asGGkqwV67Wuhulf87gGKdmcfHL2bV/WIaglVaxvpAd47J
# MDwb8PI1uGxZnP3p1sq0QB73BMrRZ6l046UIVNmDNTuOjCMMdbbehkqeGj4KUEk4
# nNKokL+Y+siMKycRfir7zt6prjiTIvqm7PtcYXbDRNbMDH4vbQaAonRAu7cf9DvX
# c1Qf8wIDAQABo4H6MIH3MA4GA1UdDwEB/wQEAwIBBjASBgNVHRMBAf8ECDAGAQH/
# AgEAMB0GA1UdDgQWBBQIbti2nIq/7T7Xw3RdzIAfqC9QejBHBgNVHSAEQDA+MDwG
# BFUdIAAwNDAyBggrBgEFBQcCARYmaHR0cHM6Ly93d3cuZ2xvYmFsc2lnbi5jb20v
# cmVwb3NpdG9yeS8wMwYDVR0fBCwwKjAooCagJIYiaHR0cDovL2NybC5nbG9iYWxz
# aWduLm5ldC9yb290LmNybDATBgNVHSUEDDAKBggrBgEFBQcDAzAfBgNVHSMEGDAW
# gBRge2YaRQ2XyolQL30EzTSo//z9SzANBgkqhkiG9w0BAQUFAAOCAQEAIlzF3T30
# C3DY4/XnxY4JAbuxljZcWgetx6hESVEleq4NpBk7kpzPuUImuztsl+fHzhFtaJHa
# jW3xU01UOIxh88iCdmm+gTILMcNsyZ4gClgv8Ej+fkgHqtdDWJRzVAQxqXgNO4yw
# cME9fte9LyrD4vWPDJDca6XIvmheXW34eNK+SZUeFXgIkfs0yL6Erbzgxt0Y2/PK
# 8HvCFDwYuAO6lT4hHj9gaXp/agOejUr58CgsMIRe7CZyQrFty2TDEozWhEtnQXyx
# Axd4CeOtqLaWLaR+gANPiPfBa1pGFc0sGYvYcJzlLUmIYHKopBlScENe2tZGA7Bo
# DiTvSvYLJSTvJDCCBFcwggM/oAMCAQICEhEhHcscxM7sz6VAvxwQtqZF6TANBgkq
# hkiG9w0BAQUFADBRMQswCQYDVQQGEwJCRTEZMBcGA1UEChMQR2xvYmFsU2lnbiBu
# di1zYTEnMCUGA1UEAxMeR2xvYmFsU2lnbiBDb2RlU2lnbmluZyBDQSAtIEcyMB4X
# DTExMDcyMjA4MjUwMloXDTE0MDcyMjA4MjUwMlowJDELMAkGA1UEBhMCQ1oxFTAT
# BgNVBAMTDEphcm9taXIgS3ViYTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoC
# ggEBAKQ2EbvEv8o5TPlCJ3cQhaUOZUgzHgB+9pya0E3VzB+URxlcpycv+xL4RTMs
# crNVhU0VCfxZxg71Cuv1O7ByiAUkhARL/KAIsIoxgQrXqlC5lnTEVZjUCo+N31cs
# YN9KPsWKbgrV6nau3jwDc2py02e4Y+qFqrK+zcscoMn4HMJsl2MfPm+JD2z7o6oi
# JcY7w8rXNKXoSz4mucS3/XVPSJHmQqQRynxg4i3tY6eigSNOtbAKjtjKxOhPeRsL
# AbJ5E7aw3mxwp39BV+ZsH02SDEnOIEdQ6WTDu4Da4iQ/ZiAvvCVp/5ZkjWfbv/oV
# poNpvUD7m+u2tAIwQ0/0u68W1+0CAwEAAaOCAVQwggFQMA4GA1UdDwEB/wQEAwIH
# gDBMBgNVHSAERTBDMEEGCSsGAQQBoDIBMjA0MDIGCCsGAQUFBwIBFiZodHRwczov
# L3d3dy5nbG9iYWxzaWduLmNvbS9yZXBvc2l0b3J5LzAJBgNVHRMEAjAAMBMGA1Ud
# JQQMMAoGCCsGAQUFBwMDMD4GA1UdHwQ3MDUwM6AxoC+GLWh0dHA6Ly9jcmwuZ2xv
# YmFsc2lnbi5jb20vZ3MvZ3Njb2Rlc2lnbmcyLmNybDBQBggrBgEFBQcBAQREMEIw
# QAYIKwYBBQUHMAKGNGh0dHA6Ly9zZWN1cmUuZ2xvYmFsc2lnbi5jb20vY2FjZXJ0
# L2dzY29kZXNpZ25nMi5jcnQwHQYDVR0OBBYEFFJQeUSszEkYXJjWSJOkhZu7f89n
# MB8GA1UdIwQYMBaAFAhu2Lacir/tPtfDdF3MgB+oL1B6MA0GCSqGSIb3DQEBBQUA
# A4IBAQBAYh1FyOGJQj0Ltlyde01s+OL1KRCQe3Z28zb6MWbXISfFkfNuLJVfdPl0
# smUtCl7D5yKX/x8Q6+h232e/+qc8xSu4lRUxwO3arYRMggDvmKauBsPH9njhwL8m
# sY0ztJtHejtNMrV1B64A3stqqW1DtvuI+YB+dTnYApRKmGg+dqeOp6qwERhSazPQ
# m1qY3V8iGYZAy8lA4XkU8DBeFyOwkH8SNMEYmcUeUSwxLkB7NM/VUE/WDPq+qMWz
# QWsYiaXi+TNNlzq12V5FqdFdooFO2K6wwuM1wc+j58cHWix1FkXzZdhN/j7Wo5t3
# SMYCStVTTZVwLgtQu44vsO0De713MIIEnzCCA4egAwIBAgISESFAXB8O0liIK+VN
# hoa6EepFMA0GCSqGSIb3DQEBBQUAMFIxCzAJBgNVBAYTAkJFMRkwFwYDVQQKExBH
# bG9iYWxTaWduIG52LXNhMSgwJgYDVQQDEx9HbG9iYWxTaWduIFRpbWVzdGFtcGlu
# ZyBDQSAtIEcyMB4XDTEzMDgyMzAwMDAwMFoXDTI0MDkyMzAwMDAwMFowYDELMAkG
# A1UEBhMCU0cxHzAdBgNVBAoTFkdNTyBHbG9iYWxTaWduIFB0ZSBMdGQxMDAuBgNV
# BAMTJ0dsb2JhbFNpZ24gVFNBIGZvciBNUyBBdXRoZW50aWNvZGUgLSBHMTCCASIw
# DQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBALAXrqLTtgQwVh5YD7HtVaTWVMvY
# 9nM67F1eqyX9NqX6hMNhQMVGtVlSO0KiLl8TYhCpW+Zz1pIlsX0j4wazhzoOQ/DX
# AIlTohExUihuXUByPPIJd6dJkpfUbJCgdqf9uNyznfIHYCxPWJgAa9MVVOD63f+A
# LF8Yppj/1KvsoUVZsi5vYl3g2Rmsi1ecqCYr2RelENJHCBpwLDOLf2iAKrWhXWvd
# jQICKQOqfDe7uylOPVOTs6b6j9JYkxVMuS2rgKOjJfuv9whksHpED1wQ119hN6pO
# a9PSUyWdgnP6LPlysKkZOSpQ+qnQPDrK6Fvv9V9R9PkK2Zc13mqF5iMEQq8CAwEA
# AaOCAV8wggFbMA4GA1UdDwEB/wQEAwIHgDBMBgNVHSAERTBDMEEGCSsGAQQBoDIB
# HjA0MDIGCCsGAQUFBwIBFiZodHRwczovL3d3dy5nbG9iYWxzaWduLmNvbS9yZXBv
# c2l0b3J5LzAJBgNVHRMEAjAAMBYGA1UdJQEB/wQMMAoGCCsGAQUFBwMIMEIGA1Ud
# HwQ7MDkwN6A1oDOGMWh0dHA6Ly9jcmwuZ2xvYmFsc2lnbi5jb20vZ3MvZ3N0aW1l
# c3RhbXBpbmdnMi5jcmwwVAYIKwYBBQUHAQEESDBGMEQGCCsGAQUFBzAChjhodHRw
# Oi8vc2VjdXJlLmdsb2JhbHNpZ24uY29tL2NhY2VydC9nc3RpbWVzdGFtcGluZ2cy
# LmNydDAdBgNVHQ4EFgQU1KKESjhaGH+6TzBQvZ3VeofWCfcwHwYDVR0jBBgwFoAU
# Rtg+/9zjvv+D5vSFm7DdatYUqcEwDQYJKoZIhvcNAQEFBQADggEBAAIxFC5YV2RB
# heivEnU8iBzDXuws6aE89bqqUx250Slj3ENnhtQ52t7Gyf++RYX0pNfBUeoY7kBY
# XuZ7zKJBKRM4yOohFpzOkKYu+6bK2ZTfQB35AhgrvvZdT5//mkjbxQUJyoDOoPnc
# S8Mj5gOPtLSvW3EpYZEYGmt68v0N0c19XpjrunBe5fTqQ941PcUUgYrbPhBeu3L6
# oaCTqwMcwWU8kROLBF0rxLkWG8xVxQzoq+dDybKDKKVTE0erOWS5HOo0MLF2AJUh
# 8dQ9qP2gADLXbpg8ppw7C4O+y7i7KiaMWbi5rq8mrOI0otwhDYELOBP3RaPj28Ss
# oW0bt+VhXNcxggSuMIIEqgIBATBnMFExCzAJBgNVBAYTAkJFMRkwFwYDVQQKExBH
# bG9iYWxTaWduIG52LXNhMScwJQYDVQQDEx5HbG9iYWxTaWduIENvZGVTaWduaW5n
# IENBIC0gRzICEhEhHcscxM7sz6VAvxwQtqZF6TAJBgUrDgMCGgUAoHgwGAYKKwYB
# BAGCNwIBDDEKMAigAoAAoQKAADAZBgkqhkiG9w0BCQMxDAYKKwYBBAGCNwIBBDAc
# BgorBgEEAYI3AgELMQ4wDAYKKwYBBAGCNwIBFTAjBgkqhkiG9w0BCQQxFgQUP+l5
# ZQ8i9nqqo8twGa535lLp7fwwDQYJKoZIhvcNAQEBBQAEggEAXj77CqsAnwOgLsfY
# m8ozO5lFrbW/4mUSTetTGM//UjmVAnPY5gePinvtuhDZ3ExDWrUTthkbC9wggLAM
# spK75aqiNCm2l6Wlqf/7C7T7PsY26vullPiy3rm3jvjLOFUwAlI8N/HqG2Uspjj9
# 65OTCPofSZHW9JgZ9fl7EsJgEh9UrsMhc7RbELYD4iHthgyEEG87GzbVtVFHXL4W
# YEWLgkvvgaEwUDTGDUgDgYZfBOVK0GJ41wYQVyi73NBarpWKzWohnf9+NK49X1Vr
# ZNRYKRRSwtjNzD1VcBzAvxiwUSJMnNEuVnfbPlXqFXJ10zZbD17SH4cuKy54xa4f
# uZ2EgaGCAqIwggKeBgkqhkiG9w0BCQYxggKPMIICiwIBATBoMFIxCzAJBgNVBAYT
# AkJFMRkwFwYDVQQKExBHbG9iYWxTaWduIG52LXNhMSgwJgYDVQQDEx9HbG9iYWxT
# aWduIFRpbWVzdGFtcGluZyBDQSAtIEcyAhIRIUBcHw7SWIgr5U2GhroR6kUwCQYF
# Kw4DAhoFAKCB/TAYBgkqhkiG9w0BCQMxCwYJKoZIhvcNAQcBMBwGCSqGSIb3DQEJ
# BTEPFw0xNDAxMTkxODM4NDdaMCMGCSqGSIb3DQEJBDEWBBT5bQyimua7C/Ufb3yD
# nmHMa0LCnzCBnQYLKoZIhvcNAQkQAgwxgY0wgYowgYcwgYQEFIzmn1AS4dGo+zle
# LjHitCveOzQ7MGwwVqRUMFIxCzAJBgNVBAYTAkJFMRkwFwYDVQQKExBHbG9iYWxT
# aWduIG52LXNhMSgwJgYDVQQDEx9HbG9iYWxTaWduIFRpbWVzdGFtcGluZyBDQSAt
# IEcyAhIRIUBcHw7SWIgr5U2GhroR6kUwDQYJKoZIhvcNAQEBBQAEggEAI76ub8Vf
# OBm3hVN79TufbouAhg6bk6zAEiB2on/z1GeAFhX9UzA4YZNyp63vG/fiiaKKpWNK
# QLynO5mHtkt66Qlkeviz4a7Zq32CqLVlsOeHUaJvk15VOG2LapJdEiwkuck+/fcp
# PMLN6wiC7eZi5/jqyikPKgwQMBhmfz6BcM5roZxruWsGFDrZTozH5krxIqmv4jvQ
# uHLut8zt4fueCbI9ie9zwLeAwRYmI5g4wnZ3znNaV+xItX80bxy4xoxmIJ+g3C74
# 8YBVtf5oNjTIsxsiVtv+AS1qm0qYLP5+c+75cTYshDzdQzDEcUG1JCWous3VkOHf
# iTW5yJYuyYryUw==
# SIG # End signature block
